-- TB_ZOO테이블 생성

CREATE TABLE TB_ZOO(

	ZOO_NO NUMBER CONSTRAINT TB_ZOO_PK PRIMARY KEY,
	ZOO_LOCATION VARCHAR2(50) NOT NULL,
	ZOO_ANIMAL VARCHAR2(50) NOT NULL,
	ANIMAL_COUNT NUMBER
);

COMMENT ON COLUMN TB_ZOO.ZOO_NO        IS '울타리번호';
COMMENT ON COLUMN TB_ZOO.ZOO_LOCATION  IS '울타리위치';
COMMENT ON COLUMN TB_ZOO.ZOO_ANIMAL    IS '동물종';
COMMENT ON COLUMN TB_ZOO.ANIMAL_COUNT  IS '마리수';


--ZOO_NO 번호 생성기SEQUENCE 만들기
CREATE SEQUENCE SEQ_ZOO_NO NOCACHE;

--샘플데이터 추가
INSERT INTO TB_ZOO
VALUES(SEQ_ZOO_NO.NEXTVAL, 'A-45','토끼',5);

INSERT INTO TB_ZOO
VALUES(SEQ_ZOO_NO.NEXTVAL, 'B-55','하마',3);

INSERT INTO TB_ZOO
VALUES(SEQ_ZOO_NO.NEXTVAL, 'D-06','사자',7);

INSERT INTO TB_ZOO
VALUES(SEQ_ZOO_NO.NEXTVAL, 'A-33','사슴',8);

INSERT INTO TB_ZOO
VALUES(SEQ_ZOO_NO.NEXTVAL, 'A-23','양',12);

INSERT INTO TB_ZOO
VALUES(SEQ_ZOO_NO.NEXTVAL, 'D-14','여우',8);

INSERT INTO TB_ZOO
VALUES(SEQ_ZOO_NO.NEXTVAL, 'D-12','호랑이',5);

INSERT INTO TB_ZOO
VALUES(SEQ_ZOO_NO.NEXTVAL, 'D-02','곰',3);

SELECT*FROM TB_ZOO;

COMMIT;



